# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5197f3cf4549fee7beffcb4027dd1bcc0aef9e3f687a0b9971a02f1d76ddb55bf99e78d6d2d3d1820ef7b31e3cc8c3f40b5b363a049d00f9be33645b651cc1

test:
  secret_key_base: 6e3829f209a929ee2d897d77c8b4604457cf136ddf640905ef9306318b28ce435ffe0676d07fe18a5301f298347a99df353b9d4d6f990b2c9488d034a7161d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
